---
title: "RSI,GARD Meta-Analysis"
output:
  pdf_document: default
  html_document:
    df_print: paged
  rmdformats: html_clean
editor_options:
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```


```{r}
library(ggplot2)
library(ggfortify)
library(gridExtra)
library(colorspace)
library(tidyverse)
library(readxl)
library(survival)

library(rms)
library(knitr)
library(rmdformats)

library(xtable)
options(xtable.floating = FALSE)
options(xtable.timestamp = "")

options(max.print="75")
opts_chunk$set(echo=FALSE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```

```{r, include = FALSE}
q <- c("#2980b9","#10ac84","#8e44ad","#95a5a6","#34495e","#b71c1c","#fb8c00","#27ae60")
swatchplot(q)
```

```{r}
# ---- summary of rms fit function ------ #
summary.fit <- function(fit){
  sum.tbl = tibble("coef"=0,"exp(coef)"=0,"se"=0,"z"=0,"chi-sq"=0,"p"=0)
  sum.tbl
  coef <- unname(fit$coefficients)
  sum.tbl["coef"] <- coef
  sum.tbl["exp(coef)"] <- exp(coef)
  se <- unname(sqrt(fit$var))
  sum.tbl["se"] <- se
  zScore <- coef/se
  sum.tbl["z"] <- zScore
  sum.tbl["p"] <- (1-pnorm(abs(zScore),0,1))*2
  sum.tbl["chi-sq"] <- anova(fit)[1,1]
  sum.tbl <- round(sum.tbl,digits=3)
  sum.tbl
}

```

```{r, fig.width=7}

# ---- loading data ------ #

load("rsi_data.rda")

# combining breast data to one site ----->
rsi.all <- rsi.all%>%
  filter(Source!="MCC") %>%
  mutate(Site = if_else(Source=="NKI_ER_neg","breast",Site)) %>%
  mutate(Site = if_else(Source=="NKI_ER_pos","breast",Site))

gard.all <- filter(rsi.all, Received_RT==1)

gard.lf <- gard.all %>%
  filter(!is.na(Event_Type)) %>%
  select(Source, Site, RSI, gard, Time, Event) %>%
  mutate(Site = as.factor(Site)) %>%
  mutate(Source = as.factor(Source))

gard.os <- gard.all %>%
  filter(!is.na(Event_OS)) %>%
  select(Source, Site, RSI, gard, Time_OS, Event_OS) %>%
  mutate(Site = as.factor(Site)) %>%
  mutate(Source = as.factor(Source))

rtNo.all <- filter(rsi.all, Received_RT==0)

rtNo.lf <- rtNo.all %>%
  filter(!is.na(Event_Type)) %>%
  select(Source, Site, RSI, gard, Time, Event) %>%
  mutate(Site = as.factor(Site)) %>%
  mutate(Source = as.factor(Source))

rtNo.os <- rtNo.all %>%
  filter(!is.na(Event_OS)) %>%
  select(Source, Site, RSI, gard, Time_OS, Event_OS) %>%
  mutate(Site = as.factor(Site)) %>%
  mutate(Source = as.factor(Source))

```


```{r kde-plot-by-site, include = TRUE, fig.width=4,fig.height=4.5}

ggplot(data=gard.all,aes(x=gard)) + 
  geom_density(adjust = 1.2, fill=rgb(.5,.5,.5,.6)) +  theme_bw() + facet_wrap(~Site, ncol=2) + coord_cartesian(xlim=c(0,80)) +
  xlab("GARD") + ylab("") +
  theme(axis.title = element_text(size=9,face="bold"),
        plot.title = element_text(size=11,face="bold"),
        axis.text.y = element_blank()) +
  ggtitle("GARD KDEs - by Site")

# ggsave(filename="gard_kde.png", width = 6, units = "in",dpi=300, path = "//")

```


```{r, fig.width=4,fig.height=3, include=TRUE}

ggplot(data=gard.all,aes(x=gard)) + 
  geom_density(adjust = 1.1,fill=rgb(.5,.5,.5,.6)) +
  theme_bw() + coord_cartesian(xlim=c(0,50)) + scale_color_brewer() + 
  theme(axis.title = element_text(size=10,face="bold"),
        plot.title = element_text(size=11,face="bold")) +
  xlab("GARD") + ylab("Density") +
  ggtitle("GARD KDE - all sites")
  
```

\newpage

## Data Summary: Outcomes by Site & Event
\bigskip
**Local Recurrence:**

```{r recurrence-table, include=TRUE, results='asis'}

all.lf <- rsi.all %>%
  filter(!is.na(Event_Type)) %>%
  select(Source, Site, Received_RT, RSI, gard, Time, Event) %>%
  mutate(Site = as.factor(Site)) %>%
  mutate(Source = as.factor(Source))

# ----- stratifying by site, +Xrt and -Xrt  ------  #
km.df <- all.lf
km <- survfit(Surv(Time,Event)~ Site, data = km.df)
t = c(1,5)
s <- summary(km,times=t)

s1<-s[c(10,2,3,4,5,6,15,16)]
s2<-data.frame(s1)
s2<- s2 %>%
  mutate(strata=sub("Site=","",strata)) %>%
  rename(site=strata)
l=length(t)
#print(xtable(s2,digits=c(0,0,0,0,0,0,3,3,3)),hline.after = c(-1,0,seq(l,nrow(s2),l)),type="latex",comment = FALSE)

#  ------ event by data / site  ------ #
z<-summary(km)$table
row.names(z) <- sub("Site=","",row.names(z))
row.names(z) <- c("Breast","Breast_TN","Endometrium","Head and Neck","NSCLC")
colnames(z)[c(1,4)] <- c('No. of patients','No. of events')

z<-z[,c(1,4)]
z<-rbind(z,"Total"=c(sum(z[,1]),sum(z[,2]),NA))
z<-cbind(z,"References"=c(NA))
kable(z)
#print(xtable(z, digits = 0),comment=FALSE,include.rownames = FALSE)

#  ------  descriptive stats at 1, 5 yr  ------ #
km <- survfit(Surv(Time,Event)~ Site + Received_RT, data = km.df)
t = c(1,5)
s <- summary(km,times=t)

s1<-s[c(10,2,3,4,5,6,15,16)]
s2<-data.frame(s1)
s2<- s2 %>%
  mutate(strata=sub("Site=","",strata)) %>%
  rename(site=strata)
s3<-s2 %>%
  select(site,time,surv) %>%
  separate(col = site,into = c('site','Xrt'), sep = ', ') %>%
  mutate(Xrt=if_else(Xrt=="Received_RT=0","Xrt-","Xrt+")) %>%
  pivot_wider(names_from = c(time,Xrt), values_from = c(surv)) %>%
  mutate(site = c("Breast","Breast_TN","Endometrium","Head and Neck","NSCLC"))
s3<-s3[,c(1,4,2,5,3)]

kable(s3,digits=3)
#print(xtable(s3,digits=3,type="latex"), comment = FALSE,include.rownames = FALSE)


```

\bigskip
**Survival:**

```{r OS-table,include=TRUE, results='asis'}

all.os <- rsi.all %>%
  filter(!is.na(Event_OS)) %>%
  select(Source, Site, Received_RT, RSI, gard, Time_OS, Event_OS) %>%
  mutate(Site = as.factor(Site)) %>%
  mutate(Source = as.factor(Source))

#  ------  stratifying only by site  ------ #
km.df <- all.os
km <- survfit(Surv(Time_OS,Event_OS)~ Site, data = km.df)
t <- c(1,5)
s <- summary(km,times=t)
s1<-s[c(10,2,3,4,5,6,15,16)]
s2<-data.frame(s1)
s2<- s2 %>%
  mutate(strata=sub("Site=","",strata)) %>%
  rename(site=strata)
l<-length(t)
#print(xtable(s2,digits=c(0,0,0,0,0,0,3,3,3)),hline.after = c(-1,0,seq(l,nrow(s2),l)),type="latex",comment = FALSE)

#  ------ event by data / site  ------ #
z<-summary(km)$table
row.names(z) <- sub("Site=","",row.names(z))
row.names(z) <- c("Breast","Breast_TN","Endometrium","Glioma","NSCLC","Pancreas")
colnames(z)[c(1,4)] <- c('No. of patients','No. of events')

z<-z[,c(1,4)]
z<-rbind(z,"Total"=c(sum(z[,1]),sum(z[,2]),NA))
z<-cbind(z,"References"=c(NA))
kable(z)
# print(xtable(z, digits = 0), comment = FALSE,include.rownames = FALSE)

#  ------ descriptive stats at 1, 5 yr  ------ #
km <- survfit(Surv(Time_OS,Event_OS)~ Site + Received_RT, data = km.df)
t = c(1,5)
s <- summary(km,times=t)

s1<-s[c(10,2,3,4,5,6,15,16)]
s2<-data.frame(s1)
s2<- s2 %>%
  mutate(strata=sub("Site=","",strata)) %>%
  rename(site=strata)
s3<-s2 %>%
  select(site,time,surv) %>%
  separate(col = site,into = c('site','Xrt'), sep = ', ') %>%
  mutate(Xrt=if_else(Xrt=="Received_RT=0","Xrt-","Xrt+")) %>%
  pivot_wider(names_from = c(time,Xrt), values_from = c(surv)) %>%
  mutate(site = c("Breast","Breast_TN","Endometrium","Glioma","NSCLC","Pancreas"))

s3<-s3[,c(1,4,2,5,3)]
kable(s3,digits=3)
# print(xtable(s3,digits=3,type="latex"), comment = FALSE,include.rownames = FALSE)

```

\newpage

## CoxPH Analysis for Individual Sites

\bigskip
 **Local-Recurrence ~ GARD**

```{r indv-site-analysis-lf, results = 'asis', include=TRUE}

data <- gard.lf
dd <- datadist(data)
options(datadist='dd')

sites <- unique(gard.lf$Site)

for (i in 1:length(sites) ) {
  val=sites[i]
  c <- cph(Surv(Time,Event) ~ gard, data = filter(data, Site == val))
  s<-summary.fit(c)
  s<-add_column(s,"site"=val,.before = 1)
  if (i==1) {
    summ.all <- s
  } else {
    summ.all <- rbind(summ.all,s)
  }
}

kable(summ.all)#, caption = "Local Recurrence - GARD")

```

 **Local-Recurrence ~ RSI**

```{r, results = 'asis', include=TRUE}

for (i in 1:length(sites) ) {
  val=sites[i]
  c <- cph(Surv(Time,Event) ~ RSI, data = filter(data, Site == val))
  s<-summary.fit(c)
  s<-add_column(s,"site"=val,.before = 1)
  if (i==1) {
    summ.all <- s
  } else {
    summ.all <- rbind(summ.all,s)
  }
}
kable(summ.all) #, caption = "Local Recurrence - RSI")

```

\bigskip
 **Survival ~ GARD**

```{r indv-site-analysis-os, results = 'asis', include=TRUE}

data <- gard.os
dd <- datadist(data)
options(datadist='dd')

sites <- unique(gard.os$Site)

for (i in 1:length(sites) ) {
  val=sites[i]
  c <- cph(Surv(Time_OS,Event_OS) ~ gard, data = filter(data, Site == val))
  s<-summary.fit(c)
  s<-add_column(s,"site"=val,.before = 1)
  if (i==1) {
    summ.all <- s
  } else {
    summ.all <- rbind(summ.all,s)
  }
}

kable(summ.all)

```

 **Survival ~ RSI**

```{r, results = 'asis', include=TRUE}

for (i in 1:length(sites) ) {
  val=sites[i]
  c <- cph(Surv(Time_OS,Event_OS) ~ RSI, data = filter(data, Site == val))
  s<-summary.fit(c)
  s<-add_column(s,"site"=val,.before = 1)
  if (i==1) {
    summ.all <- s
  } else {
    summ.all <- rbind(summ.all,s)
  }
}

kable(summ.all)

```

\newpage 

# Meta-Analysis

```{r}

stats.df <- tibble("model" = c('gard.lf','rsi.lf','gard.os','rsi.os','noRT.rsi.lf','noRT.rsi.os','noRT.gard.lf','noRT.gard.os'),
                   "coef"=0,"chisq"=0,"p"=0)

add_stats <- function(i, fit, stats.dataframe){
  stats.dataframe[i,2] <- unname(fit$coefficients)
  stats.dataframe[i,3] <- anova(fit)[1,1]
  stats.dataframe[i,4] <- anova(fit)[1,3]
  stats.dataframe
}

```

## 1. Received RT

#### (a) recurrence (any)

```{r, results='asis'}
# --------- using ~GARD ------------ #
data <- gard.lf
dd <- datadist(data)
options(datadist='dd')
fit.lf = cph(Surv(Time, Event) ~ gard + strat(Site), data = data,x=T, y=T)

stats.df <- add_stats(i=1,fit=fit.lf,stats.df)

sf.gard<-summary.fit(fit.lf)
row.names(sf.gard)<-"GARD"

p.gard <- Predict(fit.lf, gard=seq(0, 100, by = 1), Site=unique(gard.lf$Site)[1])
gg.gard.lf <- ggplot(p.gard) + theme_bw() + 
  xlab(label = "GARD") + coord_cartesian(xlim=c(0,50), ylim=c(-1.1,1.1)) + 
  ggtitle('Recurrence (Any)')

fig <- ggplot(
  Predict(fit.lf, gard=seq(0, 100, by = 1), Site=unique(gard.lf$Site),time=5),
  aes(color=Site)
  ) + facet_wrap(~Site) + theme_bw() + ggtitle("5yr Recurrence ~ GARD") + xlab("") + ylab("")

```

```{r, results='asis'}
# --------- using ~rsi ------------ #
dd <- datadist(gard.lf)
options(datadist='dd')
fit.lf = cph(Surv(Time, Event) ~ RSI + strat(Site), gard.lf, x=T, y=T)

stats.df <- add_stats(i=2,fit=fit.lf,stats.df)

sf.rsi<-summary.fit(fit.lf)
row.names(sf.rsi)<-"RSI"
kable(rbind(sf.rsi,sf.gard))

p.rsi <- Predict(fit.lf, RSI=seq(0,1,.01), Site=unique(gard.lf$Site)[1])
gg.rsi.lf <- ggplot(p.rsi, aes(color = Site)) + theme_bw() + xlab(label="RSI") +
  coord_cartesian(xlim=c(0,1), ylim=c(-1,1.6))  + ggtitle('Recurrence (Any)')
```

```{r, fig.width = 6}
# gard by-site plot
fig
```

#### (b) survival

``` {r, echo = FALSE, results='asis'}
# --------- using ~gard ------------ #
data<- gard.os
dd <- datadist(data)
options(datadist='dd')
fit.os = cph(Surv(Time_OS, Event_OS) ~ gard + strat(Site), data, x=T, y=T)

stats.df <- add_stats(i=3,fit=fit.os,stats.df)

sf.gard<-summary.fit(fit.os)
row.names(sf.gard)<-"GARD"

p <- Predict(fit.os, gard=seq(0, 100, by = 1), Site=unique(gard.os$Site)[1])
gg.gard.os <- ggplot(p, aes(group = Site)) + theme_bw() + xlab(label = "GARD") + 
   ggtitle('Survival') + coord_cartesian(xlim=c(0,50), ylim=c(-1.1,1.1))

fig<- ggplot(
  Predict(fit.os, gard=seq(0, 100, by = 1), Site=unique(gard.os$Site),time=5),
  aes(color=Site)
) + facet_wrap(~Site) + theme_bw() + ggtitle("5 yr OS ~ GARD") + xlab("") + ylab("")

```

```{r, results='asis'}
# --------- using ~rsi ------------ #
data<- gard.os
dd <- datadist(data)
options(datadist='dd')
fit.os = cph(Surv(Time_OS, Event_OS) ~ RSI + strat(Site), data, x=T, y=T)

stats.df <- add_stats(i=4,fit=fit.os,stats.df)

sf.rsi<-summary.fit(fit.os)
row.names(sf.rsi)<-"RSI"
kable(rbind(sf.rsi,sf.gard))

p <- Predict(fit.os, RSI=seq(0,1,.01), Site=unique(gard.os$Site)[1])
gg.rsi.os <- ggplot(p, aes(color = Site)) +  theme_bw() + 
  coord_cartesian(xlim=c(0,1), ylim=c(-1,1.6)) +
  xlab(label="RSI") + ggtitle('Survival')
```

```{r, fig.width=6}
# plotting gard OS by site
fig
```


## 2. No RT Received
#### (a) recurrence
```{r, results='asis'}
# ---------- using gard ----------- #
data<- rtNo.lf
dd <- datadist(data)
options(datadist='dd')
fit.lf = cph(Surv(Time, Event) ~ gard + strat(Site), data, x=T, y=T)

stats.df <- add_stats(i=7,fit=fit.lf,stats.df)

sf.gard<-summary.fit(fit.lf)
row.names(sf.gard)<-"GARD"

# ---------- using RSI ---------- #
data<- rtNo.lf
dd <- datadist(data)
options(datadist='dd')
fit.lf = cph(Surv(Time, Event) ~ RSI + strat(Site), data, x=T, y=T)

stats.df <- add_stats(i=5,fit=fit.lf,stats.df)

sf.rsi<-summary.fit(fit.lf)
row.names(sf.rsi)<-"RSI"

kable(rbind(sf.rsi,sf.gard))

p <- Predict(fit.lf, RSI=seq(0,1,.01), Site=unique(gard.lf$Site)[1])
gg.noRT.lf <- ggplot(p, aes(group = Site)) +  theme_bw() +
  coord_cartesian(xlim=c(0,1), ylim=c(-1.5,2.4)) + 
  xlab(label="RSI") + ggtitle('Recurrence (No RT)')

```

#### (b) survival

``` {r, results='asis'}

# ---------- using gard ---------- #
data <- rtNo.os
dd <- datadist(data)
options(datadist='dd')
fit.os = cph(Surv(Time_OS, Event_OS) ~ gard + strat(Site), data, x=T, y=T)

stats.df <- add_stats(i=8,fit=fit.os,stats.df)

sf.gard<-summary.fit(fit.os)
row.names(sf.gard)<-"GARD"

# ---------- using RSI ---------- #
data <- rtNo.os
dd <- datadist(data)
options(datadist='dd')
fit.os = cph(Surv(Time_OS, Event_OS) ~ RSI + strat(Site), data, x=T, y=T)

stats.df <- add_stats(i=6,fit=fit.os,stats.df)

sf.rsi<-summary.fit(fit.os)
row.names(sf.rsi)<-"RSI"

kable(rbind(sf.rsi,sf.gard))

p <- Predict(fit.os, RSI=seq(0,1,.01), Site=unique(gard.lf$Site)[1])
gg.noRT.os <- ggplot(p, aes(group = Site)) +  theme_bw() + 
  coord_cartesian(xlim=c(0,1), ylim=c(-1.5,2.4)) + 
  xlab(label="RSI") + ggtitle('Survival (No RT)')
```

\newpage
# Figures for Linear Models

```{r, results='asis'}

# ------ latex table for manuscript -------- #

#stats.df
stats.table<-stats.df %>%
  mutate(Xrt = if_else(grepl("noRT",model),"-Xrt","+Xrt"))%>%
  select(!coef) %>%
  mutate(chisq = round(chisq,1)) %>%
  mutate(p = round(p,3)) %>%
  unite(col = "chisq_p",sep = ", quad ", c('chisq','p')) %>%
  pivot_wider(names_from = Xrt, values_from = chisq_p) %>%
  mutate(model = c("Recurrence (GARD)", "Recurrence (RSI)","Survival (GARD)","Survival (RSI)",
                   "noRT Recurrence (RSI)","noRT Survival (RSI)","noRT Recurrence (GARD)","noRT Survival (GARD)"))

#stats.table
stats.table<-cbind(stats.table[c(2,1,3,4),],stats.table[c(5,7,6,8),])

print(xtable(stats.table[,c(1,2,6)]), comment=FALSE,include.rownames = FALSE)

```

``` {r gard-fig,  fig.width=7, fig.height=4}


j=1
g1 <- gg.gard.lf + 
  geom_path(color=q[1]) +
  theme(axis.title = element_text(size=12, face="bold")) +
  theme(plot.title = element_text(size=14, face="bold")) +
  annotate("rect", xmin = 3, xmax = 28, ymin = -.98, ymax = -.52, alpha = .1) +
  annotate(geom="text",x = 5, y = -.75, 
           hjust="left",  size=3,
           label = sprintf("Coef = %.3f \nChi-Sq = %.1f \nP = %.3f", stats.df[j,2],stats.df[j,3],stats.df[j,4])) 
j=3          
g2 <- gg.gard.os + ylab(label="") +
  geom_path(color=q[1]) +
  theme(axis.title = element_text(size=12,face="bold")) +
  theme(plot.title = element_text(size=14,face="bold")) +
  annotate("rect", xmin = 3, xmax = 28, ymin = -1, ymax = -.5, alpha = .1) +
  annotate(geom="text",x = 5, y = -.75, 
           hjust="left", size=3,
           label = sprintf("Coef = %.3f \nChi-Sq = %.1f \nP = %.3f",stats.df[j,2],stats.df[j,3],stats.df[j,4]))

grid.arrange(g1, g2, nrow=1)

g <- arrangeGrob(g1, g2, nrow=1)
# ggsave(plot = g, path = 'Figures',
#        filename="GARD_alloutcome.png",
#        width = 6, height = 4, units = "in",
#        dpi=300)
```

```{r rsi-fig, fig.width=7, fig.height=4}
j=2
g1 <- gg.rsi.lf + 
  geom_path(color=q[6]) +
  theme(axis.title = element_text(size=12, face="bold")) +
  theme(plot.title = element_text(size=14,face="bold")) +
  annotate("rect", xmin = .6, xmax = 1, ymin = -.95, ymax = -.45, alpha = .1) +
  annotate(geom="text",x = .64, y = -.71, 
           hjust="left", size=3,
           label = sprintf("Coef = %.3f \nChi-Sq = %.1f \nP = %.3f", stats.df[j,2],stats.df[j,3],stats.df[j,4]))
j=4
g2 <- gg.rsi.os + ylab(label="") +
  geom_path(color=q[6]) +
  theme(axis.title = element_text(size=12,face="bold")) +
  theme(plot.title = element_text(size=14,face="bold")) +
  annotate("rect", xmin = .6, xmax = 1, ymin = -.95, ymax = -.45, alpha = .1) +
  annotate(geom="text",x = .64, y = -.71, 
           hjust="left", size=3, 
           label = sprintf("Coef = %.3f \nChi-Sq = %.1f \nP = %.3f",stats.df[j,2],stats.df[j,3],stats.df[j,4]))

grid.arrange(g1, g2, nrow=1)

g <- arrangeGrob(g1, g2, nrow=1)
# ggsave(plot = g,
#        filename="RSI_alloutcome.png",
#        width = 6,height = 4,units = "in",
#        path = "Figures",
#        dpi=300)

```

```{r noRT-fig, fig.width=7, fig.height=4}
# fig3 - RSI, no RT
j=5
g1 <- gg.noRT.lf +
  geom_path(color=q[2]) +
  theme(axis.title = element_text(size=12,face="bold")) +
  theme(plot.title = element_text(size=14,face="bold")) +
  annotate("rect", xmin = .04, xmax = .42, ymin = 1.58, ymax = 2.22, alpha = .1) +
  annotate(geom="text",x = .06, y = 1.9, 
           hjust="left", size=3,
           label = sprintf("Coef = %.3f \nChi-Sq = %.1f \nP = %.3f", stats.df[j,2],stats.df[j,3],stats.df[j,4]))

j=6
g2 <- gg.noRT.os + ylab(label="") +
  geom_path(color=q[2]) +
  theme(axis.title = element_text(size=12,face="bold")) +
  theme(plot.title = element_text(size=14,face="bold")) +
  annotate("rect", xmin = .04, xmax = .42, ymin = 1.58, ymax = 2.22, alpha = .1) +
  annotate(geom="text",x = .06, y = 1.9,
           hjust="left", size=3,
           label = sprintf("Coef = %.3f \nChi-Sq = %.1f \nP = %.3f", stats.df[j,2],stats.df[j,3],stats.df[j,4]))

grid.arrange(g1, g2, nrow=1)

g <- arrangeGrob(g1, g2, nrow=1)
# ggsave(plot = g,
#        filename="NoRT_RSI_alloutcome.png",
#        width = 6,height = 4,units = "in",
#        path = "Figures",
#        dpi=300)

```